# Nome da Action
name: Snake Game

# Controlador do tempo: atualiza√ß√£o a cada 5 horas
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do reposit√≥rio
      - uses: actions/checkout@v4

      # Gera os arquivos do Snake Game
      - uses: Platane/snk@v3.2.0  # Recomendo usar uma vers√£o est√°vel, verifique a mais recente
        id: snake-gif
        with:
          github_user_name: pygaudiello
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verifica o status do git (informativo)
      - run: git status

      # Faz push das altera√ß√µes
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Mensagem informativa
      - name: Run a multi-line script
        run: |
          echo "‚úÖ Workflow conclu√≠do."
          echo "üéØ Verifique os arquivos gerados na pasta 'dist' no branch 'main'."
